#TODO
# Ensure acl is installed on the master node
- hosts: master
  become: yes
  become_method: sudo
  tasks:
    - name: check if cluster is initialized
      stat:
        path: $HOME/.kube
      register: kube_config

    - name: init cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16
      args:
        chdir: $HOME
        creates: cluster_initialized.txt
      when: not kube_config.stat.exists

    - name: create .kube home driver
      become: yes
      become_user: kuber
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copies admin.conf to user's kube # https://kubernetes.io/docs/concepts/configuration/configmap/
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/kuber/.kube/config
        remote_src: yes
        owner: kuber

    - name: install pod network
      become: yes
      become_user: kuber
      shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      args:
        chdir: $HOME

    - name: Get the token for joining the worker nodes
      become: yes
      become_user: kuber
      shell: |
        kubeadm token create --print-join-command > /tmp/join_command.sh
        cat /tmp/join_command.sh

    - name: Fetch join command to control machine
      fetch:
        src: /tmp/join_command.sh
        dest: ./join_command.sh
        flat: yes

    - name: Set up kubeconfig for root
      shell: |
        mkdir -p $HOME/.kube
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config